In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/e-commerce-shoppers-behaviour-understanding/test_data_v2.csv
/kaggle/input/e-commerce-shoppers-behaviour-understanding/train_data_v2.csv
/kaggle/input/e-commerce-shoppers-behaviour-understanding/sample.csv


In [2]:
train_df = pd.read_csv("/kaggle/input/e-commerce-shoppers-behaviour-understanding/train_data_v2.csv")
train_df.head()

HomePage  HomePage_Duration  LandingPage  LandingPage_Duration  \
0       0.0                0.0          0.0                   0.0   
1       0.0                0.0          0.0                   0.0   
2       0.0                0.0          0.0                   0.0   
3       0.0                0.0          0.0                   0.0   
4       1.0                0.0          0.0                   0.0   

   ProductDescriptionPage  ProductDescriptionPage_Duration  \
0                     1.0                         0.000000   
1                     2.0                         2.666667   
2                    10.0                       627.500000   
3                     1.0                         0.000000   
4                     0.0                         0.000000   

   GoogleMetric:Bounce Rates  GoogleMetric:Exit Rates  \
0                       0.20                     0.20   
1                       0.05                     0.14   
2                       0.02                     0.05   
3                       0.20                     0.20   
4                       0.20                     0.20   

   GoogleMetric:Page Values  SeasonalPurchase  ... SearchEngine  Zone  \
0                       0.0               0.0  ...          1.0   9.0   
1                       0.0               0.0  ...          2.0   2.0   
2                       0.0               0.0  ...          3.0   1.0   
3                       0.0               0.4  ...          4.0   3.0   
4                       0.0               0.0  ...          2.0   1.0   

   Type of Traffic       CustomerType         Gender Cookies Setting  \
0              3.0  Returning_Visitor  Not Specified            Deny   
1              4.0  Returning_Visitor         Female            Deny   
2              4.0  Returning_Visitor         Female             ALL   
3              3.0  Returning_Visitor           Male             ALL   
4              5.0  Returning_Visitor           Male            Deny   

       Education Marital Status WeekendPurchase Made_Purchase  
0  Not Specified          Other             0.0         False  
1         Others        Married             0.0         False  
2         Others        Married             1.0         False  
3        Diploma         Single             0.0         False  
4        Diploma          Other             1.0         False  

[5 rows x 22 columns]

In [3]:
train_df.shape

(14731, 22)

In [4]:
train_df.columns

Index(['HomePage', 'HomePage_Duration', 'LandingPage', 'LandingPage_Duration',
       'ProductDescriptionPage', 'ProductDescriptionPage_Duration',
       'GoogleMetric:Bounce Rates', 'GoogleMetric:Exit Rates',
       'GoogleMetric:Page Values', 'SeasonalPurchase',
       'Month_SeasonalPurchase', 'OS', 'SearchEngine', 'Zone',
       'Type of Traffic', 'CustomerType', 'Gender', 'Cookies Setting',
       'Education', 'Marital Status', 'WeekendPurchase', 'Made_Purchase'],
      dtype='object')

In [5]:
X, y = train_df.iloc[:, :-1], train_df.iloc[:, -1]
X.shape, y.shape

((14731, 21), (14731,))

In [6]:
X.head()

HomePage  HomePage_Duration  LandingPage  LandingPage_Duration  \
0       0.0                0.0          0.0                   0.0   
1       0.0                0.0          0.0                   0.0   
2       0.0                0.0          0.0                   0.0   
3       0.0                0.0          0.0                   0.0   
4       1.0                0.0          0.0                   0.0   

   ProductDescriptionPage  ProductDescriptionPage_Duration  \
0                     1.0                         0.000000   
1                     2.0                         2.666667   
2                    10.0                       627.500000   
3                     1.0                         0.000000   
4                     0.0                         0.000000   

   GoogleMetric:Bounce Rates  GoogleMetric:Exit Rates  \
0                       0.20                     0.20   
1                       0.05                     0.14   
2                       0.02                     0.05   
3                       0.20                     0.20   
4                       0.20                     0.20   

   GoogleMetric:Page Values  SeasonalPurchase  ...   OS  SearchEngine  Zone  \
0                       0.0               0.0  ...  4.0           1.0   9.0   
1                       0.0               0.0  ...  3.0           2.0   2.0   
2                       0.0               0.0  ...  3.0           3.0   1.0   
3                       0.0               0.4  ...  2.0           4.0   3.0   
4                       0.0               0.0  ...  1.0           2.0   1.0   

   Type of Traffic       CustomerType         Gender Cookies Setting  \
0              3.0  Returning_Visitor  Not Specified            Deny   
1              4.0  Returning_Visitor         Female            Deny   
2              4.0  Returning_Visitor         Female             ALL   
3              3.0  Returning_Visitor           Male             ALL   
4              5.0  Returning_Visitor           Male            Deny   

       Education Marital Status WeekendPurchase  
0  Not Specified          Other             0.0  
1         Others        Married             0.0  
2         Others        Married             1.0  
3        Diploma         Single             0.0  
4        Diploma          Other             1.0  

[5 rows x 21 columns]

In [7]:
y.head()

0    False
1    False
2    False
3    False
4    False
Name: Made_Purchase, dtype: bool

In [8]:
from sklearn.dummy import DummyClassifier
dummy_clf = DummyClassifier(strategy="prior")
dummy_clf

DummyClassifier()

In [9]:
dummy_clf.fit(X, y)

DummyClassifier()

In [10]:
y_pred = dummy_clf.predict(X)

In [11]:
from sklearn.metrics import classification_report

In [12]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

       False       0.62      1.00      0.76      9065
        True       0.00      0.00      0.00      5666

    accuracy                           0.62     14731
   macro avg       0.31      0.50      0.38     14731
weighted avg       0.38      0.62      0.47     14731



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


`Test file`  

In [13]:
test_df = pd.read_csv("/kaggle/input/e-commerce-shoppers-behaviour-understanding/test_data_v2.csv")
test_df.head()

HomePage  HomePage_Duration  LandingPage  LandingPage_Duration  \
0       0.0                0.0          0.0                   0.0   
1       0.0                0.0          0.0                   0.0   
2       0.0                0.0          0.0                   0.0   
3       0.0                0.0          0.0                   0.0   
4       0.0                0.0          0.0                   0.0   

   ProductDescriptionPage  ProductDescriptionPage_Duration  \
0                     1.0                         0.000000   
1                     2.0                        64.000000   
2                    19.0                       154.216667   
3                     2.0                        37.000000   
4                    16.0                       407.750000   

   GoogleMetric:Bounce Rates  GoogleMetric:Exit Rates  \
0                   0.200000                 0.200000   
1                   0.000000                 0.100000   
2                   0.015789                 0.024561   
3                   0.000000                 0.100000   
4                   0.018750                 0.025833   

   GoogleMetric:Page Values  SeasonalPurchase  ...   OS  SearchEngine  Zone  \
0                       0.0               0.0  ...  1.0           1.0   1.0   
1                       0.0               0.0  ...  2.0           2.0   1.0   
2                       0.0               0.0  ...  2.0           2.0   1.0   
3                       0.0               0.8  ...  2.0           2.0   2.0   
4                       0.0               0.4  ...  1.0           1.0   4.0   

   Type of Traffic       CustomerType         Gender Cookies Setting  \
0              1.0  Returning_Visitor  Not Specified            Deny   
1              2.0  Returning_Visitor  Not Specified             ALL   
2              3.0  Returning_Visitor         Female        Required   
3              3.0  Returning_Visitor  Not Specified        Required   
4              3.0  Returning_Visitor         Female            Deny   

       Education Marital Status WeekendPurchase  
0  Not Specified         Single             0.0  
1       Graduate        Married             0.0  
2        Diploma          Other             0.0  
3       Graduate          Other             0.0  
4         Others          Other             0.0  

[5 rows x 21 columns]

In [14]:
test_df.shape

(6599, 21)

In [15]:
test_df.columns

Index(['HomePage', 'HomePage_Duration', 'LandingPage', 'LandingPage_Duration',
       'ProductDescriptionPage', 'ProductDescriptionPage_Duration',
       'GoogleMetric:Bounce Rates', 'GoogleMetric:Exit Rates',
       'GoogleMetric:Page Values', 'SeasonalPurchase',
       'Month_SeasonalPurchase', 'OS', 'SearchEngine', 'Zone',
       'Type of Traffic', 'CustomerType', 'Gender', 'Cookies Setting',
       'Education', 'Marital Status', 'WeekendPurchase'],
      dtype='object')

In [16]:
X_test = test_df
X_test.shape

(6599, 21)

In [17]:
y_test = dummy_clf.predict(X_test)
y_test

array([False, False, False, ..., False, False, False])

In [18]:
y_test.shape

(6599,)

In [19]:
submission = pd.DataFrame(y_test, columns=["Made_Purchase"])
submission.index.names = ["id"]
submission

Made_Purchase
id                 
0             False
1             False
2             False
3             False
4             False
...             ...
6594          False
6595          False
6596          False
6597          False
6598          False

[6599 rows x 1 columns]

In [20]:
submission.to_csv("/kaggle/working/submission.csv")

`Dummy classifier 2`  

In [21]:
dummy_clf_2 = DummyClassifier(strategy="constant", constant=True)
dummy_clf_2

DummyClassifier(constant=True, strategy='constant')

In [22]:
dummy_clf_2.fit(X, y)

DummyClassifier(constant=True, strategy='constant')

In [23]:
y_test_2 = dummy_clf_2.predict(X_test)
y_test_2

array([ True,  True,  True, ...,  True,  True,  True])

In [24]:
submission = pd.DataFrame(y_test_2, columns=["Made_Purchase"])
submission.index.names = ["id"]
submission

Made_Purchase
id                 
0              True
1              True
2              True
3              True
4              True
...             ...
6594           True
6595           True
6596           True
6597           True
6598           True

[6599 rows x 1 columns]

In [25]:
submission.to_csv("/kaggle/working/submission.csv")

`Random prediction`  

In [26]:
y.value_counts()

False    9065
True     5666
Name: Made_Purchase, dtype: int64

In [27]:
import random
y_random_array= np.array([random.choice([True, False]) for i in range(6599)])
y_random_array

array([False,  True,  True, ..., False,  True,  True])

In [28]:
submission = pd.DataFrame(y_random_array, columns=["Made_Purchase"])
submission.index.names = ["id"]
submission

Made_Purchase
id                 
0             False
1              True
2              True
3             False
4              True
...             ...
6594          False
6595           True
6596          False
6597           True
6598           True

[6599 rows x 1 columns]

In [29]:
submission.value_counts()

Made_Purchase
False            3383
True             3216
dtype: int64

In [30]:
submission.to_csv("/kaggle/working/submission.csv")